<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui" />
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="//cdn.firebase.com/libs/firebaseui/3.1.1/firebaseui.css" />
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <script src="//www.gstatic.com/firebasejs/5.4.0/firebase-app.js"></script>
    <script src="//www.gstatic.com/firebasejs/5.4.0/firebase-auth.js"></script>
    <script src="//cdn.firebase.com/libs/firebaseui/3.1.1/firebaseui.js"></script>
    <script type="text/javascript" src="/js/entrance.js"></script>
    <script type="text/javascript" src="/js/recordWorker.js"></script>
    <script type="text/javascript" src="/js/recorder.js"></script>
    <script type="text/javascript" src="/js/audio.js"></script>

    <title>::cognetic.io::</title>

</head>

<body>

<h1>Recorder.js simple WAV export example</h1>

<p>Make sure you are using a recent version of Google Chrome.</p>
<p>Also before you enable microphone input either plug in headphones or turn the volume down if you want to avoid ear splitting feedback!</p>

<button onclick="startRecording(this);">record</button>
<button onclick="stopRecording(this);">stop</button>

<h2>Recordings</h2>
<ul id="recordingslist"></ul>

<h2>Log</h2>
<pre id="log"></pre>

<script type="application/javascript">
    function __log(e, data) {
        log.innerHTML += "\n" + e + " " + (data || '');
    }

    var audio_context;
    var recorder;

    function startUserMedia(stream) {
        var input = audio_context.createMediaStreamSource(stream);
        input.connect(audio_context.destination);
        recorder = new Recorder(input);
        __log('Recorder initialised.');
    }

    function startRecording(button) {
        recorder.record();
        __log('Recording...');
    }

    function stopRecording(button) {
        recorder.stop();
        __log('Stopped recording.');

        // create WAV download link using audio data blob
        createDownloadLink();

    }


    function createDownloadLink() {
        recorder.exportMonoWAV(function (blob) {

            var fd = new FormData();
            fd.append('fname', 'test.wav');
            fd.append('data', blob);
            $.ajax({
                type: 'POST',
                url: '/audio',
                data: fd,
                processData: false,
                contentType: false
            }).done(function(data) {
                for (var x =0; x < data.length; x++) {
                    $.get("/concept?w=" + data[x], function (d) {
                           for (var zx =0; zx < d.length; zx++) {
			  	var i = document.createElement("img");
 				i.src = d[zx];
				document.getElementById('xx').appendChild(i);
			}
			//document.getElementById("fooba").innerText += JSON.stringify(d);
                    });
                }
                document.getElementById("fooba").innerText = JSON.stringify(data);
            });

        }, 'pcm');
    }

    window.onload = function init() {
        try {
            // webkit shim
            window.AudioContext = window.AudioContext || window.webkitAudioContext;
            window.URL = window.URL || window.webkitURL;
            audio_context = new AudioContext;
            navigator.mediaDevices.getUserMedia({audio: true, video: false}).then(startUserMedia);
        } catch (e) {
            alert('No web audio support in this browser!');
        }
    };
</script>


<span id="fooba"></span>
<div id="xx"></div>
</body>
</html>
