<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui" />
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="//cdn.firebase.com/libs/firebaseui/3.1.1/firebaseui.css" />
    <script src="//www.gstatic.com/firebasejs/5.4.0/firebase-app.js"></script>
    <script src="//www.gstatic.com/firebasejs/5.4.0/firebase-auth.js"></script>
    <script src="//www.gstatic.com/firebasejs/5.4.0/firebase-firestore.js"></script>
    <script src="//cdn.firebase.com/libs/firebaseui/3.1.1/firebaseui.js"></script>
    <script type="text/javascript" src="/js/entrance.js"></script>
    <title>::cognetic.io::</title>
    <style>
        body {
            background-color: #f5e9db;
        }

        button {
            width: 45%;
            background-color: aqua;
            margin: auto;
        }


        h1 {
            font-size: 4em !important;
        }

        #scoreCard, #countRemain {
            font-size: 100px;
            line-height: 100px;
        }

        .age {
            margin: 5px;
        }

        .overlay {
            position: absolute;
            background-color: whitesmoke;
            z-index: 1;
            opacity: 0.93;
            width: 100%;
            height: 100%;
        }

        .content-area {
            position: absolute;
            top: 0;
            left: 50%;
            width: 85%;
            transform: translate(-50%, 30%);
            z-index: 2;
        }

        .content-area2 {
            position: absolute;
            top: 70%;
            left: 50%;
            width: 80%;
            transform: translate(-50%,-20%);
            z-index: 2;
        }

        .content-area h2 {
            font-size: 50px;
        }

        .content-area button {
            z-index: 2;
        }

        #correct {
            font-size: 100px;
        }

        .col-sm-12 {
            /*width: 50%;*/
            /*margin: auto;*/
            /*vertical-align: middle;*/
            /*height: 4em;*/
            /*border: black 1px solid;*/
            /*border-radius: 10px;*/
            /*font-size: 3em;*/
            background-color: white;
        }

        .bottom {
            display: block;
            max-width: 100%;
            width: 100%;
            position: absolute;
            bottom:20px;
            left:50%;
            transform:translateX(-50%);
            z-index: 0;
        }

        .bottom2 {
            /*display: block;*/
            /*max-width: 100%;*/
            /*width: 100%;*/
            /*position: absolute;*/
            /*bottom: 0;*/
            /*left:50%;*/
            /*transform:translateX(-50%);*/
            /*z-index: 0;*/

            display: inline-flex;
            max-width: 100%;
            width: 100%;
            position: fixed;
            bottom: 0;
            left: 50%;
            transform: translateX(-50%);
            z-index: 2;
            /* height: 10%; */
            vertical-align: bottom;
            margin-bottom: 0px;
            padding-bottom: 0px;
        }
        /*span {*/
        /*margin: auto;*/
        /*top: 5em;*/
        /*font-size: 1em;*/
        /*position: absolute;*/
        /*width: 50%;*/
        /*height: auto;*/
        /*}*/
        .lst {
            display: none;
        }

        .firebaseui-card-content {
            height: 500px;
        }

        .blue { color: blue; }
        .green { color: green; }
        .yellow { color: yellow; }
        .red { color: red; }
        .black { color: black; }

        .bgblue { background-color: white; }
        .bggreen { background-color: white; }
        .bgyellow { background-color: white; }
        .bgred { background-color: white; }
        .bgblack { background-color: white; }

        #divNumber {
            background-image: url(/images/celebrate.png);
            background-repeat-y: no-repeat;
            background-blend-mode: darken;
        }

        .pulse {
            background-color: black;
        }

    </style>



</head>

<body>
<canvas name="id">

</canvas>

</body>
</html>