<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui" />
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="//cdn.firebase.com/libs/firebaseui/3.1.1/firebaseui.css" />

    <title>cognetic.io</title>
    <style>
        body {
            background-color: #f5e9db;
        }

        button {
            width: 45%;
            background-color: aqua;
            margin: auto;
        }


        h1 {
            font-size: 4em !important;
        }

        #scoreCard, #countRemain {
            font-size: 100px;
            line-height: 100px;
        }

        .age {
            margin: 5px;
        }

        .overlay {
            position: absolute;
            background-color: whitesmoke;
            z-index: 1;
            opacity: 0.93;
            width: 100%;
            height: 100%;
        }

        .content-area {
            position: absolute;
            top: 40%;
            left: 50%;
            width: 85%;
            transform: translate(-50%,-50%);
            z-index: 2;
        }

        .content-area2 {
            position: absolute;
            top: 70%;
            left: 50%;
            width: 80%;
            transform: translate(-50%,-20%);
            z-index: 2;
        }

        .content-area h2 {
            font-size: 50px;
        }

        .content-area button {
            z-index: 2;
        }

        #correct {
            font-size: 100px;
        }

        .col-sm-12 {
            /*width: 50%;*/
            /*margin: auto;*/
            /*vertical-align: middle;*/
            /*height: 4em;*/
            /*border: black 1px solid;*/
            /*border-radius: 10px;*/
            /*font-size: 3em;*/
            background-color: white;
        }

        .bottom {
            display: block;
            max-width: 100%;
            width: 100%;
            position: absolute;
            bottom:20px;
            left:50%;
            transform:translateX(-50%);
            z-index: 0;
        }

        .bottom2 {
            /*display: block;*/
            /*max-width: 100%;*/
            /*width: 100%;*/
            /*position: absolute;*/
            /*bottom: 0;*/
            /*left:50%;*/
            /*transform:translateX(-50%);*/
            /*z-index: 0;*/

            display: inline-flex;
            max-width: 100%;
            width: 100%;
            position: fixed;
            bottom: 0;
            left: 50%;
            transform: translateX(-50%);
            z-index: 2;
            /* height: 10%; */
            vertical-align: bottom;
            margin-bottom: 0px;
            padding-bottom: 0px;
        }
        /*span {*/
            /*margin: auto;*/
            /*top: 5em;*/
            /*font-size: 1em;*/
            /*position: absolute;*/
            /*width: 50%;*/
            /*height: auto;*/
        /*}*/
        .lst {
            display: none;
        }

        .firebaseui-card-content {
            height: 500px;
        }

        .blue { color: blue; }
        .green { color: green; }
        .yellow { color: yellow; }
        .red { color: red; }
        .black { color: black; }

        .bgblue { background-color: white; }
        .bggreen { background-color: white; }
        .bgyellow { background-color: white; }
        .bgred { background-color: white; }
        .bgblack { background-color: white; }
    </style>
</head>
<body>
<script type="text/javascript">


    window.addEventListener('load', function() {
        // Initialize Firebase
        var config = {
            apiKey: "AIzaSyBd855hO36BuuAXfQcudIM0qXV9X8EIbII",
            authDomain: "cogneticio.firebaseapp.com",
            databaseURL: "https://cogneticio.firebaseio.com",
            projectId: "cogneticio",
            storageBucket: "cogneticio.appspot.com",
            messagingSenderId: "1088761305754"
        };
        var app = firebase.initializeApp(config);
        var uiConfig = {
            callbacks: {
                // signInSuccessWithAuthResult: function(authResult, redirectUrl) {
                //     // User successfully signed in.
                //     // Return type determines whether we continue the redirect automatically
                //     // or whether we leave that to developer to handle.
                //     return true;
                // },
                // uiShown: function() {
                //     // The widget is rendered.
                //     // Hide the loader.
                //    // document.getElementById('loader').style.display = 'none';
                // }
            },
            // Will use popup for IDP Providers sign-in flow instead of the default, redirect.
            //signInFlow: 'popup',
            signInSuccessUrl: 'local.cognetic.io:8858/dashboard',
            signInOptions: {
                autoUpgradeAnonymousUsers: true,
                provider: [
                    firebase.auth.EmailAuthProvider.PROVIDER_ID,
                    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
                    firebase.auth.FacebookAuthProvider.PROVIDER_ID
                ],
                //requireDisplayName: false
            }

            // Terms of service url.
            ///tosUrl: '<your-tos-url>',
            // Privacy policy url.
            //privacyPolicyUrl: '<your-privacy-policy-url>'
        };

        var ui = new firebaseui.auth.AuthUI(app.auth());
        // The start method will wait until the DOM is loaded.
        ui.start('#firebaseui-auth-container', uiConfig);
    });
</script>
    <div id="firebaseui-auth-container" style="display: block; height: 500px; width: 100%">

    </div>
    <div id="ageGroups" class="overlay text-center" style="display: none;">
        <h2 class="h2">Are you Color Blind?</h2>
        <img src="/images/logo.png" />
        <div class="content-area2">
            <h5 class="h5">Please select your age group.</h5>
            <button class="btn btn-primary age">below 13</button>
            <button class="btn btn-primary age">13 - 17</button>
            <button class="btn btn-primary age">17 - 30</button>
            <button class="btn btn-primary age">30 - 45</button>
            <button class="btn btn-primary age">45 - 65</button>
            <button class="btn btn-primary age">65+</button>
        </div>
    </div>
    <div id="divCount" class="overlay text-center" style="display: none;">
        <div class="content-area">
            <div id="countRemain"></div>
        </div>
    </div>
    <div class="overlay" id="firebaseAuth" style="display: none;">
        <h1>Welcome to My Awesome App</h1>
        <div id="loader">Loading...</div>

    </div>
    <div id="divNumber" class="overlay text-center" style="display: none; padding-top: 20px">
        <h2 class="h2 text-center col-sm-12" style="color: green;background-color: transparent;">GOAL</h2>
        <div class="content-area" style="/* top: 45%; */">
            <div id="scoreCard">100</div>
            <div id="remark" style="font-size: 12px;"> (see below for in-depth details)</div>
            <hr>
            <h3 class="h3 text-left">Continue to</h3>
            <div style="height: 5px;">&nbsp;</div>

            <div class="col-sm-12 text-left" style="width: 100%;margin: 5px 0px 5px 0px;font-size: 14px;z-index: 2;background-color: transparent;">
                - win a GIFT* <br>
                - play 100+ activities<br>
                - challenge friends and family <br>
                - improve attention*** <br>
                - get a gym report****<br>
            </div>
        </div>
        <div class="content-area" style="transform: translate(-50%, 0%);bottom: -20%; z-index: 2;/* top: 10%; */top: 75%;">
            <div class="fb-login-button" onclick="fireb();" data-max-rows="1" data-size="medium" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
            <div style="width: 100%; height: 5px;">&nbsp;</div>
            <button id="googleb" onclick="fireb();" class="col-sm-7 btn btn-primary btn-red">Google Sign</button>
        </div>
        <div class="bottom2 col-sm-12 text-center" style="font-size: 10px">GESIT - A Gems production. State of Cognition is a registered trademark of GESIT</div>
    </div>

    <div class="container" id="mainContainer" style="display: none;">
        <div class="col-sm-11 text-right" style="height: 100px; font-size: 36px; color: white;" id="game-seconds">90</div>
        <div class="col-sm-6 text-center shadow-lg bg-white rounded">
            <h1 class="h1" id="first"></h1>
        </div>

        <div class="col-sm-11">&nbsp;</div>

        <div class="col-sm-6 text-center shadow-lg bg-white rounded">
            <h1 id="second" class="h1"></h1>
        </div>


        <div class="col-sm-10 text-center" style="height: 110px"><span id="correct"></span></div>
        <div id="dvBottom" class="bottom text-center" style="display: none">
            <button class="btn btn-primary btn-lg shadow-lg rounded btno" id="no">No</button>
            <button class="btn btn-primary btn-lg shadow-lg rounded btys" id="yes">Yes</button>
        </div>
    </div>
    <audio id="adcorrect">
        <source id="sound1" src="sounds/correct.mp3" type="audio/mpeg">
    </audio>
    <audio id="adbust">
        <source id="sound2" src="sounds/bust.mp3" type="audio/mpeg">
    </audio>
    <audio id="adcountdown">
        <source id="sound3" src="sounds/countdown.mp3" type="audio/mpeg">
    </audio>
    <audio id="adtick">
        <source id="sound4" src="sounds/tick.mp3" type="audio/mpeg">
    </audio>
<script src="https://www.gstatic.com/firebasejs/5.4.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/5.4.0/firebase-auth.js"></script>

    <script src="//cdn.firebase.com/libs/firebaseui/3.1.1/firebaseui.js"></script>
        <script type="application/javascript">

        var c = 3;
        var round = 0;
        var c4, c5;
        var check = "\u2713";
        var cross = "\u2718";
        var cls = ["black", "red", "blue", "yellow"];
        var gameseconds = 3;
        var roundScore = 100;
        var gametimer;
        var age = document.getElementById("ageGroups");
        var divScore = document.getElementById("divNumber");
        var divCounter = document.getElementById("divCount");
        var dvBottom = document.getElementById("dvBottom");
        var cro = document.getElementById("correct");
        var scoreCard = document.getElementById("scoreCard");
        var countRemain = document.getElementById("countRemain");
        var firebaseAuth = document.getElementById('firebaseAuth');
        var firebaseUi = document.getElementById('firebaseui-auth-container');

        var mainContainer = document.getElementById('mainContainer');

        <?php printf("var map = %s;", $map); ?>

        var effects = {tick: "tick", correct: "correct", bust: "bust", countdown: "countdown"};

        var firsttext, secondtext;
        var score = 0;
        var streak = 0;

        function play(f, cb) {
            var effects = document.getElementById("ad" + f);
            effects.play();
            if (cb !== undefined && cb !== null) {
                effects.onended = cb;
            }
        }

        function first(text, text2) {
            document.getElementById("first").innerText = text;
            document.getElementById("second").innerText = text2;
            firsttext = text;
        }
        function secondColor(name) {
            secondtext = name;
            document.getElementById("second").className = cls[c] + " text-center";
        }
        function second(text) {
            document.getElementById("second").innerText = text;
        }
        function getRandomInt(max) {
            return Math.floor(Math.random() * Math.floor(max));
        }
        function color()
        {
            var rand = getRandomInt(100);
            if (rand < 40) c = 0;
            else if (rand >= 40 && rand < 65) c = 1;
            else if (rand >= 65 && rand < 90) c = 2;
            else if (rand >= 90 && rand <= 100) c = 3;
            return map[c];
        }

        function setup() {
            round++;
            var c1 = color();
            var c2 = color();
            var c3 = color();
            first(c1, c2);
            secondColor(c3);
            c4 = c3;
            c5 = c1;
        }



        function correct() {
            streak++;
            if (streak > 1 && streak % 10 === 0) gameseconds += 2;
            var tmpstreak = streak;
            if (tmpstreak > 5) tmpstreak = 5;
            score += (roundScore * tmpstreak);
            showHide(check, "green");
            play(effects.correct, function () {
                cro.style.display = "none";
            });
        }
        function wrong() {
            streak = 0;
            --gameseconds;
            showHide(cross, "red");
            play(effects.bust, function () {
                cro.style.display = "none";
            });
        }
        function showHide(text, color, stay) {
            cro.innerText = text;
            cro.style.color = color;
            cro.style.display = "block";
        }
        function overlay(text) {
            scoreCard.innerText = text;
            divScore.style.display = "block";
            // divScore.onclick = function () {
            //   this.style.display = "none";
            // };
        }

        function countdown() {
            age.style.display = "none";
            divCount.style.display = "block";
            countRemain.innerText = 3;
            gametimer = setInterval(function () {

                var foo = parseInt(countRemain.innerText);
                if (foo === 0) {
                    clearInterval(gametimer);
                    return init();
                } else {
                    play(effects.countdown);
                    countRemain.innerText = --foo;
                }

            }, 1000);
        }

        function init() {
            document.getElementById("correct").style.display = "none";
            divCounter.style.display = "none";
            dvBottom.style.display = "block";
            setup();
            gametimer = window.setInterval(function () {
                if (gameseconds <= 5) {
                    play(effects.tick, null);
                }
                if (gameseconds === 0) {
                    overlay(score);
                    return clearInterval(gametimer);
                }
                gameseconds--;
                document.getElementById("game-seconds").innerText = gameseconds;

            }, 1000);
        }
        function fireb() {
            divNumber.style.display = "none";
            mainContainer.style.display = "none";
            //firebaseAuth.style.display = "block";
            firebaseUi.style.display = "block";

        }
        document.getElementsByClassName("btys")[0].onclick = function (ev) {
            if (firsttext === secondtext) {
                correct();
            } else {
                wrong();
            }
            setup();
        };
        document.getElementsByClassName("btno")[0].onclick = function (ev) {
            if (firsttext !== secondtext) {
                correct();
            } else {
                wrong();
            }
            setup();
        };
        // window.onload = function () {
        //   var ageGroup = document.getElementsByClassName("age");
        //   for (var i = 0; i < ageGroup.length; i++) {
        //      if (ageGroup[i].className.indexOf("age") !== -1) {
        //          ageGroup[i].onclick = function () {
        //              countdown();
        //          };
        //      }
        //   };
        // };


        // authService.createUserWithEmailAndPassword(email, password).catch(function(error) {
        //     // Handle Errors here.
        //     var errorCode = error.code;
        //     var errorMessage = error.message;
        //
        // });

       // authService.auth().currentUser;
        // window.fbAsyncInit = function() {
        //     FB.init({
        //         appId      : '662709724090948',
        //         cookie     : true,
        //         xfbml      : true,
        //     });
        //
        //     FB.AppEvents.logPageView();
        //
        //     FB.getLoginStatus(function(response) {
        //         statusChangeCallback(response);
        //     });
        //
        // };

</script>
</body>
</html>