<html>
    <head>
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui" />
        <title>COGNETIC.IO</title>
        <style>
            body {
                margin: 0;
                padding: 0;
                background-color: black;
                color: white;
                font-size: 132px;
                font-weight: 700;
                width: 100%;
                text-align:center;
                line-height: 132px;
            }

            .links {
                font-size: 60px;
            }

            a:visited, a:hover, a:active, a {
                color: white;
            }
        </style>
    </head>
    <body>
        <DIV class=links>[<a href="/vision">VISION</a>]</DIV>
        <DIV class=links>[<a href="/memory">MEMORY</a>]</DIV>
        <br/><br/>
        <div>COGNETIC.IO</div>
    </body>
</html>
